"""empty message

Revision ID: 7bb6822a1b51
Revises: 2c7911bd78a9
Create Date: 2018-07-29 13:39:24.018473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb6822a1b51'
down_revision = '2c7911bd78a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('gender', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'gender')
    # ### end Alembic commands ###
